#pragma once
void hello_world();
void variable();
void input_output();
void arithmetic();
void if_statement();
void switch_statement();
void string_function();
void math_function();
void logical_operator();
void while_loop();
void for_loop();
void nested_loop();
void printf_function();